server:
  port: ${PORT:8080}

spring:
  application:
    name: Project_ITSS
    api-prefix: /api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

vnPay:
  url: ${VNPAY_URL}
  returnUrl: ${VNPAY_RETURNURL}
  tmnCode: ${VNPAY_TMNCODE}
  secretKey: ${VNPAY_HASHSECRET}
  version: 2.1.0
  command: pay
  orderType: other
  currCode: VND
  locale: vn
  apiUrl: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  timeoutExpress: 15
